module.exports = {
    "up": "CREATE TABLE IF NOT EXISTS posts ( id INT NOT NULL AUTO_INCREMENT , uuid VARCHAR(255) NOT NULL, user VARCHAR(255) NOT NULL , post TEXT NOT NULL ,  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , status INT(1) NULL DEFAULT NULL , location VARCHAR(255) NULL DEFAULT NULL, attachment VARCHAR(255) NULL DEFAULT NULL, post_type VARCHAR(255) NULL DEFAULT 'post', PRIMARY KEY (id)) ENGINE = InnoDB;",
    "down": "DROP TABLE posts"
}