module.exports = {
    "up": "CREATE TABLE IF NOT EXISTS password_reset (id INT NOT NULL AUTO_INCREMENT, uuid VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, code VARCHAR(255) NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, status INT(1) NOT NULL DEFAULT '0' , PRIMARY KEY (id)) ENGINE = InnoDB;",
    "down": "DROP TABLE password_reset"
}