module.exports = {
    "up": "CREATE TABLE IF NOT EXISTS polls ( id INT NOT NULL AUTO_INCREMENT , uuid VARCHAR(255) NOT NULL , sector VARCHAR(255) NOT NULL , opinion TEXT NOT NULL , created_by VARCHAR(255) NOT NULL , created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , expire_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP , status INT(1) NOT NULL DEFAULT 0 , response_limit INT(255) NULL , PRIMARY KEY (id)) ENGINE = InnoDB",
    "down": "DROP TABLE polls"
}