module.exports = {
    "up": "CREATE TABLE IF NOT EXISTS petitions (id INT NOT NULL AUTO_INCREMENT, uuid VARCHAR(255) NOT NULL, user VARCHAR(255) NOT NULL, targeted_office VARCHAR(255) NOT NULL, petition_class VARCHAR(255) NOT NULL, petition_title TEXT NOT NULL, attachment VARCHAR(255) NULL DEFAULT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, status INT(1) NOT NULL DEFAULT '0' , PRIMARY KEY (id)) ENGINE = InnoDB;",
    "down": "DROP TABLE petitions"
}