module.exports = {
    "up": "CREATE TABLE IF NOT EXISTS comments ( id INT NOT NULL AUTO_INCREMENT , uuid VARCHAR(255) NOT NULL , comment TEXT NOT NULL , created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , status INT NULL DEFAULT '1' , ref VARCHAR(255) NOT NULL , user VARCHAR(255) NOT NULL , PRIMARY KEY (id), UNIQUE (uuid)) ENGINE = InnoDB;",
    "down": "DROP TABLE comments"
}